ccflags-y += -Idrivers/media/platform/msm/camera_v1
ccflags-y += -Idrivers/media/platform/msm/camera_v1/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v1/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
