ccflags-y += -Idrivers/media/platform/msm/camera_v1
ccflags-y += -Idrivers/media/platform/msm/camera_v1/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v1/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
